## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
   datasource:
     url: jdbc:mysql://localhost:3306/travel?useSSL=false
     username: root
     password: rootpassworduser
   jpa:
     properties:
       hibernate:
         jdbc:
           lob.non_contextual_creation: true
         dialect: org.hibernate.dialect.MySQL5Dialect
         ddl-auto: update
         format_sql: true
   servlet:
     multipart:
       enabled: true
       file-size-threshold: 5KB
       max-file-size: 200MB
       max-request-size: 215MB
   mail:
     host: smtp.gmail.com
     port: 587
     username: snlshvsnj@gmail.com
     password: DuMMyPwd
     properties:
       mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
           enable: true
     defaultEncoding: UTF-8

# SSL, post 465
#spring.mail.properties.mail.smtp.socketFactory.port = 465
#spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory


logging:
  level:
   org:
    hibernate:
     SQL: DEBUG
     type:
       descriptor:
        sql:
         BasicBinder: TRACE

jwt:
  app:
    jwtSecret: narsimha
    jwtExpirationMs: 600000

server:
  port: 2020

